version: '3.9'

services:
  web:
    container_name: task_manager
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      - app_static:/app/staticfiles
      - app_media:/app/media

    environment:
      - DJANGO_SETTINGS_MODULE=task_manager.settings
    expose:
      - "8000"  # Internal port for Django/Daphne
    env_file:
      - .env
    networks:
      - task_manager

  nginx:
    image: nginx:alpine
    container_name: task_manager_nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Mount single file
      - app_static:/app/staticfiles  # Changed path to match Nginx config
      - app_media:/app/media    # Changed path to match Nginx config
    depends_on:
      - web
    networks:
      - task_manager

networks:
  task_manager:
    driver: bridge

volumes:
  app_static:
  app_media: